function plotFunctionPitcher() {
pitcher = document.getElementById("pitcher_heat_maps").value
if (pitcher=="112526"){document.getElementById("pitch_heat").src = "static/pitcher_images/Bartolo Colon_zone_frequency.png";}
if (pitcher=="112526"){document.getElementById("pitch_bar").src = "static/pitcher_images/Bartolo Colon_zone_frequency_bar.png";}
if (pitcher=="276351"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jason Grilli_zone_frequency.png";}
if (pitcher=="276351"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jason Grilli_zone_frequency_bar.png";}
if (pitcher=="276542"){document.getElementById("pitch_heat").src = "static/pitcher_images/Joaquin Benoit_zone_frequency.png";}
if (pitcher=="276542"){document.getElementById("pitch_bar").src = "static/pitcher_images/Joaquin Benoit_zone_frequency_bar.png";}
if (pitcher=="279571"){document.getElementById("pitch_heat").src = "static/pitcher_images/Matt Belisle_zone_frequency.png";}
if (pitcher=="279571"){document.getElementById("pitch_bar").src = "static/pitcher_images/Matt Belisle_zone_frequency_bar.png";}
if (pitcher=="282332"){document.getElementById("pitch_heat").src = "static/pitcher_images/CC Sabathia_zone_frequency.png";}
if (pitcher=="282332"){document.getElementById("pitch_bar").src = "static/pitcher_images/CC Sabathia_zone_frequency_bar.png";}
if (pitcher=="285064"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ryan Vogelsong_zone_frequency.png";}
if (pitcher=="285064"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ryan Vogelsong_zone_frequency_bar.png";}
if (pitcher=="285079"){document.getElementById("pitch_heat").src = "static/pitcher_images/R.A. Dickey_zone_frequency.png";}
if (pitcher=="285079"){document.getElementById("pitch_bar").src = "static/pitcher_images/R.A. Dickey_zone_frequency_bar.png";}
if (pitcher=="407793"){document.getElementById("pitch_heat").src = "static/pitcher_images/John Lackey_zone_frequency.png";}
if (pitcher=="407793"){document.getElementById("pitch_bar").src = "static/pitcher_images/John Lackey_zone_frequency_bar.png";}
if (pitcher=="407845"){document.getElementById("pitch_heat").src = "static/pitcher_images/Fernando Rodney_zone_frequency.png";}
if (pitcher=="407845"){document.getElementById("pitch_bar").src = "static/pitcher_images/Fernando Rodney_zone_frequency_bar.png";}
if (pitcher=="407890"){document.getElementById("pitch_heat").src = "static/pitcher_images/Colby Lewis_zone_frequency.png";}
if (pitcher=="407890"){document.getElementById("pitch_bar").src = "static/pitcher_images/Colby Lewis_zone_frequency_bar.png";}
if (pitcher=="407908"){document.getElementById("pitch_heat").src = "static/pitcher_images/Joel Peralta_zone_frequency.png";}
if (pitcher=="407908"){document.getElementById("pitch_bar").src = "static/pitcher_images/Joel Peralta_zone_frequency_bar.png";}
if (pitcher=="408061"){document.getElementById("pitch_heat").src = "static/pitcher_images/Francisco Rodriguez_zone_frequency.png";}
if (pitcher=="408061"){document.getElementById("pitch_bar").src = "static/pitcher_images/Francisco Rodriguez_zone_frequency_bar.png";}
if (pitcher=="408241"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jake Peavy_zone_frequency.png";}
if (pitcher=="408241"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jake Peavy_zone_frequency_bar.png";}
if (pitcher=="425426"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chien-Ming Wang_zone_frequency.png";}
if (pitcher=="425426"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chien-Ming Wang_zone_frequency_bar.png";}
if (pitcher=="425492"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ryan Madson_zone_frequency.png";}
if (pitcher=="425492"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ryan Madson_zone_frequency_bar.png";}
if (pitcher=="425626"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chris Capuano_zone_frequency.png";}
if (pitcher=="425626"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chris Capuano_zone_frequency_bar.png";}
if (pitcher=="425657"){document.getElementById("pitch_heat").src = "static/pitcher_images/Javier Lopez_zone_frequency.png";}
if (pitcher=="425657"){document.getElementById("pitch_bar").src = "static/pitcher_images/Javier Lopez_zone_frequency_bar.png";}
if (pitcher=="425794"){document.getElementById("pitch_heat").src = "static/pitcher_images/Adam Wainwright_zone_frequency.png";}
if (pitcher=="425794"){document.getElementById("pitch_bar").src = "static/pitcher_images/Adam Wainwright_zone_frequency_bar.png";}
if (pitcher=="425844"){document.getElementById("pitch_heat").src = "static/pitcher_images/Zack Greinke_zone_frequency.png";}
if (pitcher=="425844"){document.getElementById("pitch_bar").src = "static/pitcher_images/Zack Greinke_zone_frequency_bar.png";}
if (pitcher=="425856"){document.getElementById("pitch_heat").src = "static/pitcher_images/Gavin Floyd_zone_frequency.png";}
if (pitcher=="425856"){document.getElementById("pitch_bar").src = "static/pitcher_images/Gavin Floyd_zone_frequency_bar.png";}
if (pitcher=="429722"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ervin Santana_zone_frequency.png";}
if (pitcher=="429722"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ervin Santana_zone_frequency_bar.png";}
if (pitcher=="430580"){document.getElementById("pitch_heat").src = "static/pitcher_images/Alfredo Simon_zone_frequency.png";}
if (pitcher=="430580"){document.getElementById("pitch_bar").src = "static/pitcher_images/Alfredo Simon_zone_frequency_bar.png";}
if (pitcher=="430589"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chad Qualls_zone_frequency.png";}
if (pitcher=="430589"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chad Qualls_zone_frequency_bar.png";}
if (pitcher=="430599"){document.getElementById("pitch_heat").src = "static/pitcher_images/Joe Blanton_zone_frequency.png";}
if (pitcher=="430599"){document.getElementById("pitch_bar").src = "static/pitcher_images/Joe Blanton_zone_frequency_bar.png";}
if (pitcher=="430641"){document.getElementById("pitch_heat").src = "static/pitcher_images/Blaine Boyer_zone_frequency.png";}
if (pitcher=="430641"){document.getElementById("pitch_bar").src = "static/pitcher_images/Blaine Boyer_zone_frequency_bar.png";}
if (pitcher=="430912"){document.getElementById("pitch_heat").src = "static/pitcher_images/Matt Cain_zone_frequency.png";}
if (pitcher=="430912"){document.getElementById("pitch_bar").src = "static/pitcher_images/Matt Cain_zone_frequency_bar.png";}
if (pitcher=="430935"){document.getElementById("pitch_heat").src = "static/pitcher_images/Cole Hamels_zone_frequency.png";}
if (pitcher=="430935"){document.getElementById("pitch_bar").src = "static/pitcher_images/Cole Hamels_zone_frequency_bar.png";}
if (pitcher=="431148"){document.getElementById("pitch_heat").src = "static/pitcher_images/Scott Kazmir_zone_frequency.png";}
if (pitcher=="431148"){document.getElementById("pitch_bar").src = "static/pitcher_images/Scott Kazmir_zone_frequency_bar.png";}
if (pitcher=="432934"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chris Young_zone_frequency.png";}
if (pitcher=="432934"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chris Young_zone_frequency_bar.png";}
if (pitcher=="433579"){document.getElementById("pitch_heat").src = "static/pitcher_images/John Danks_zone_frequency.png";}
if (pitcher=="433579"){document.getElementById("pitch_bar").src = "static/pitcher_images/John Danks_zone_frequency_bar.png";}
if (pitcher=="433586"){document.getElementById("pitch_heat").src = "static/pitcher_images/Santiago Casilla_zone_frequency.png";}
if (pitcher=="433586"){document.getElementById("pitch_bar").src = "static/pitcher_images/Santiago Casilla_zone_frequency_bar.png";}
if (pitcher=="433587"){document.getElementById("pitch_heat").src = "static/pitcher_images/Felix Hernandez_zone_frequency.png";}
if (pitcher=="433587"){document.getElementById("pitch_bar").src = "static/pitcher_images/Felix Hernandez_zone_frequency_bar.png";}
if (pitcher=="433589"){document.getElementById("pitch_heat").src = "static/pitcher_images/Yusmeiro Petit_zone_frequency.png";}
if (pitcher=="433589"){document.getElementById("pitch_bar").src = "static/pitcher_images/Yusmeiro Petit_zone_frequency_bar.png";}
if (pitcher=="434378"){document.getElementById("pitch_heat").src = "static/pitcher_images/Justin Verlander_zone_frequency.png";}
if (pitcher=="434378"){document.getElementById("pitch_bar").src = "static/pitcher_images/Justin Verlander_zone_frequency_bar.png";}
if (pitcher=="434538"){document.getElementById("pitch_heat").src = "static/pitcher_images/Francisco Liriano_zone_frequency.png";}
if (pitcher=="434538"){document.getElementById("pitch_bar").src = "static/pitcher_images/Francisco Liriano_zone_frequency_bar.png";}
if (pitcher=="434622"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ubaldo Jimenez_zone_frequency.png";}
if (pitcher=="434622"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ubaldo Jimenez_zone_frequency_bar.png";}
if (pitcher=="434628"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jason Hammel_zone_frequency.png";}
if (pitcher=="434628"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jason Hammel_zone_frequency_bar.png";}
if (pitcher=="434671"){document.getElementById("pitch_heat").src = "static/pitcher_images/Anibal Sanchez_zone_frequency.png";}
if (pitcher=="434671"){document.getElementById("pitch_bar").src = "static/pitcher_images/Anibal Sanchez_zone_frequency_bar.png";}
if (pitcher=="434718"){document.getElementById("pitch_heat").src = "static/pitcher_images/Huston Street_zone_frequency.png";}
if (pitcher=="434718"){document.getElementById("pitch_bar").src = "static/pitcher_images/Huston Street_zone_frequency_bar.png";}
if (pitcher=="435043"){document.getElementById("pitch_heat").src = "static/pitcher_images/Zach Duke_zone_frequency.png";}
if (pitcher=="435043"){document.getElementById("pitch_bar").src = "static/pitcher_images/Zach Duke_zone_frequency_bar.png";}
if (pitcher=="444436"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ryan Webb_zone_frequency.png";}
if (pitcher=="444436"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ryan Webb_zone_frequency_bar.png";}
if (pitcher=="444468"){document.getElementById("pitch_heat").src = "static/pitcher_images/Hector Rondon_zone_frequency.png";}
if (pitcher=="444468"){document.getElementById("pitch_bar").src = "static/pitcher_images/Hector Rondon_zone_frequency_bar.png";}
if (pitcher=="444520"){document.getElementById("pitch_heat").src = "static/pitcher_images/Craig Breslow_zone_frequency.png";}
if (pitcher=="444520"){document.getElementById("pitch_bar").src = "static/pitcher_images/Craig Breslow_zone_frequency_bar.png";}
if (pitcher=="444857"){document.getElementById("pitch_heat").src = "static/pitcher_images/Scott Feldman_zone_frequency.png";}
if (pitcher=="444857"){document.getElementById("pitch_bar").src = "static/pitcher_images/Scott Feldman_zone_frequency_bar.png";}
if (pitcher=="445060"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ricky Nolasco_zone_frequency.png";}
if (pitcher=="445060"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ricky Nolasco_zone_frequency_bar.png";}
if (pitcher=="445276"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kenley Jansen_zone_frequency.png";}
if (pitcher=="445276"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kenley Jansen_zone_frequency_bar.png";}
if (pitcher=="445926"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jesse Chavez_zone_frequency.png";}
if (pitcher=="445926"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jesse Chavez_zone_frequency_bar.png";}
if (pitcher=="445968"){document.getElementById("pitch_heat").src = "static/pitcher_images/Dana Eveland_zone_frequency.png";}
if (pitcher=="445968"){document.getElementById("pitch_bar").src = "static/pitcher_images/Dana Eveland_zone_frequency_bar.png";}
if (pitcher=="446099"){document.getElementById("pitch_heat").src = "static/pitcher_images/John Axford_zone_frequency.png";}
if (pitcher=="446099"){document.getElementById("pitch_bar").src = "static/pitcher_images/John Axford_zone_frequency_bar.png";}
if (pitcher=="446321"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ross Detwiler_zone_frequency.png";}
if (pitcher=="446321"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ross Detwiler_zone_frequency_bar.png";}
if (pitcher=="446372"){document.getElementById("pitch_heat").src = "static/pitcher_images/Corey Kluber_zone_frequency.png";}
if (pitcher=="446372"){document.getElementById("pitch_bar").src = "static/pitcher_images/Corey Kluber_zone_frequency_bar.png";}
if (pitcher=="446399"){document.getElementById("pitch_heat").src = "static/pitcher_images/Brett Cecil_zone_frequency.png";}
if (pitcher=="446399"){document.getElementById("pitch_bar").src = "static/pitcher_images/Brett Cecil_zone_frequency_bar.png";}
if (pitcher=="446899"){document.getElementById("pitch_heat").src = "static/pitcher_images/Brad Ziegler_zone_frequency.png";}
if (pitcher=="446899"){document.getElementById("pitch_bar").src = "static/pitcher_images/Brad Ziegler_zone_frequency_bar.png";}
if (pitcher=="447714"){document.getElementById("pitch_heat").src = "static/pitcher_images/Eric O'Flaherty_zone_frequency.png";}
if (pitcher=="447714"){document.getElementById("pitch_bar").src = "static/pitcher_images/Eric O'Flaherty_zone_frequency_bar.png";}
if (pitcher=="448178"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kevin Jepsen_zone_frequency.png";}
if (pitcher=="448178"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kevin Jepsen_zone_frequency_bar.png";}
if (pitcher=="448179"){document.getElementById("pitch_heat").src = "static/pitcher_images/Rich Hill_zone_frequency.png";}
if (pitcher=="448179"){document.getElementById("pitch_bar").src = "static/pitcher_images/Rich Hill_zone_frequency_bar.png";}
if (pitcher=="448281"){document.getElementById("pitch_heat").src = "static/pitcher_images/Sean Doolittle_zone_frequency.png";}
if (pitcher=="448281"){document.getElementById("pitch_bar").src = "static/pitcher_images/Sean Doolittle_zone_frequency_bar.png";}
if (pitcher=="448306"){document.getElementById("pitch_heat").src = "static/pitcher_images/James Shields_zone_frequency.png";}
if (pitcher=="448306"){document.getElementById("pitch_bar").src = "static/pitcher_images/James Shields_zone_frequency_bar.png";}
if (pitcher=="448609"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tony Sipp_zone_frequency.png";}
if (pitcher=="448609"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tony Sipp_zone_frequency_bar.png";}
if (pitcher=="448614"){document.getElementById("pitch_heat").src = "static/pitcher_images/Carlos Torres_zone_frequency.png";}
if (pitcher=="448614"){document.getElementById("pitch_bar").src = "static/pitcher_images/Carlos Torres_zone_frequency_bar.png";}
if (pitcher=="448802"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jaime Garcia_zone_frequency.png";}
if (pitcher=="448802"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jaime Garcia_zone_frequency_bar.png";}
if (pitcher=="449097"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jonathan Papelbon_zone_frequency.png";}
if (pitcher=="449097"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jonathan Papelbon_zone_frequency_bar.png";}
if (pitcher=="449104"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jim Henderson_zone_frequency.png";}
if (pitcher=="449104"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jim Henderson_zone_frequency_bar.png";}
if (pitcher=="450172"){document.getElementById("pitch_heat").src = "static/pitcher_images/Edinson Volquez_zone_frequency.png";}
if (pitcher=="450172"){document.getElementById("pitch_bar").src = "static/pitcher_images/Edinson Volquez_zone_frequency_bar.png";}
if (pitcher=="450203"){document.getElementById("pitch_heat").src = "static/pitcher_images/Charlie Morton_zone_frequency.png";}
if (pitcher=="450203"){document.getElementById("pitch_bar").src = "static/pitcher_images/Charlie Morton_zone_frequency_bar.png";}
if (pitcher=="450212"){document.getElementById("pitch_heat").src = "static/pitcher_images/Pat Neshek_zone_frequency.png";}
if (pitcher=="450212"){document.getElementById("pitch_bar").src = "static/pitcher_images/Pat Neshek_zone_frequency_bar.png";}
if (pitcher=="450275"){document.getElementById("pitch_heat").src = "static/pitcher_images/Mark Lowe_zone_frequency.png";}
if (pitcher=="450275"){document.getElementById("pitch_bar").src = "static/pitcher_images/Mark Lowe_zone_frequency_bar.png";}
if (pitcher=="450308"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jered Weaver_zone_frequency.png";}
if (pitcher=="450308"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jered Weaver_zone_frequency_bar.png";}
if (pitcher=="450665"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kris Medlen_zone_frequency.png";}
if (pitcher=="450665"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kris Medlen_zone_frequency_bar.png";}
if (pitcher=="450729"){document.getElementById("pitch_heat").src = "static/pitcher_images/Doug Fister_zone_frequency.png";}
if (pitcher=="450729"){document.getElementById("pitch_bar").src = "static/pitcher_images/Doug Fister_zone_frequency_bar.png";}
if (pitcher=="451085"){document.getElementById("pitch_heat").src = "static/pitcher_images/Brian Matusz_zone_frequency.png";}
if (pitcher=="451085"){document.getElementById("pitch_bar").src = "static/pitcher_images/Brian Matusz_zone_frequency_bar.png";}
if (pitcher=="451584"){document.getElementById("pitch_heat").src = "static/pitcher_images/Wade Davis_zone_frequency.png";}
if (pitcher=="451584"){document.getElementById("pitch_bar").src = "static/pitcher_images/Wade Davis_zone_frequency_bar.png";}
if (pitcher=="451661"){document.getElementById("pitch_heat").src = "static/pitcher_images/Josh Fields_zone_frequency.png";}
if (pitcher=="451661"){document.getElementById("pitch_bar").src = "static/pitcher_images/Josh Fields_zone_frequency_bar.png";}
if (pitcher=="451775"){document.getElementById("pitch_heat").src = "static/pitcher_images/Fernando Rodriguez_zone_frequency.png";}
if (pitcher=="451775"){document.getElementById("pitch_bar").src = "static/pitcher_images/Fernando Rodriguez_zone_frequency_bar.png";}
if (pitcher=="452657"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jon Lester_zone_frequency.png";}
if (pitcher=="452657"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jon Lester_zone_frequency_bar.png";}
if (pitcher=="452666"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tom Wilhelmsen_zone_frequency.png";}
if (pitcher=="452666"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tom Wilhelmsen_zone_frequency_bar.png";}
if (pitcher=="453178"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ian Kennedy_zone_frequency.png";}
if (pitcher=="453178"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ian Kennedy_zone_frequency_bar.png";}
if (pitcher=="453192"){document.getElementById("pitch_heat").src = "static/pitcher_images/Andrew Miller_zone_frequency.png";}
if (pitcher=="453192"){document.getElementById("pitch_bar").src = "static/pitcher_images/Andrew Miller_zone_frequency_bar.png";}
if (pitcher=="453214"){document.getElementById("pitch_heat").src = "static/pitcher_images/Steven Wright_zone_frequency.png";}
if (pitcher=="453214"){document.getElementById("pitch_bar").src = "static/pitcher_images/Steven Wright_zone_frequency_bar.png";}
if (pitcher=="453222"){document.getElementById("pitch_heat").src = "static/pitcher_images/Scott Carroll_zone_frequency.png";}
if (pitcher=="453222"){document.getElementById("pitch_bar").src = "static/pitcher_images/Scott Carroll_zone_frequency_bar.png";}
if (pitcher=="453249"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jeff Manship_zone_frequency.png";}
if (pitcher=="453249"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jeff Manship_zone_frequency_bar.png";}
if (pitcher=="453265"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tony Watson_zone_frequency.png";}
if (pitcher=="453265"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tony Watson_zone_frequency_bar.png";}
if (pitcher=="453286"){document.getElementById("pitch_heat").src = "static/pitcher_images/Max Scherzer_zone_frequency.png";}
if (pitcher=="453286"){document.getElementById("pitch_bar").src = "static/pitcher_images/Max Scherzer_zone_frequency_bar.png";}
if (pitcher=="453329"){document.getElementById("pitch_heat").src = "static/pitcher_images/Clay Buchholz_zone_frequency.png";}
if (pitcher=="453329"){document.getElementById("pitch_bar").src = "static/pitcher_images/Clay Buchholz_zone_frequency_bar.png";}
if (pitcher=="453343"){document.getElementById("pitch_heat").src = "static/pitcher_images/Mark Melancon_zone_frequency.png";}
if (pitcher=="453343"){document.getElementById("pitch_bar").src = "static/pitcher_images/Mark Melancon_zone_frequency_bar.png";}
if (pitcher=="453385"){document.getElementById("pitch_heat").src = "static/pitcher_images/Clayton Richard_zone_frequency.png";}
if (pitcher=="453385"){document.getElementById("pitch_bar").src = "static/pitcher_images/Clayton Richard_zone_frequency_bar.png";}
if (pitcher=="453562"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jake Arrieta_zone_frequency.png";}
if (pitcher=="453562"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jake Arrieta_zone_frequency_bar.png";}
if (pitcher=="453646"){document.getElementById("pitch_heat").src = "static/pitcher_images/Carlos Villanueva_zone_frequency.png";}
if (pitcher=="453646"){document.getElementById("pitch_bar").src = "static/pitcher_images/Carlos Villanueva_zone_frequency_bar.png";}
if (pitcher=="455009"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jonathan Broxton_zone_frequency.png";}
if (pitcher=="455009"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jonathan Broxton_zone_frequency_bar.png";}
if (pitcher=="455374"){document.getElementById("pitch_heat").src = "static/pitcher_images/Antonio Bastardo_zone_frequency.png";}
if (pitcher=="455374"){document.getElementById("pitch_bar").src = "static/pitcher_images/Antonio Bastardo_zone_frequency_bar.png";}
if (pitcher=="456027"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ross Ohlendorf_zone_frequency.png";}
if (pitcher=="456027"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ross Ohlendorf_zone_frequency_bar.png";}
if (pitcher=="456034"){document.getElementById("pitch_heat").src = "static/pitcher_images/David Price_zone_frequency.png";}
if (pitcher=="456034"){document.getElementById("pitch_bar").src = "static/pitcher_images/David Price_zone_frequency_bar.png";}
if (pitcher=="456379"){document.getElementById("pitch_heat").src = "static/pitcher_images/Al Alburquerque_zone_frequency.png";}
if (pitcher=="456379"){document.getElementById("pitch_bar").src = "static/pitcher_images/Al Alburquerque_zone_frequency_bar.png";}
if (pitcher=="456501"){document.getElementById("pitch_heat").src = "static/pitcher_images/Johnny Cueto_zone_frequency.png";}
if (pitcher=="456501"){document.getElementById("pitch_bar").src = "static/pitcher_images/Johnny Cueto_zone_frequency_bar.png";}
if (pitcher=="456696"){document.getElementById("pitch_heat").src = "static/pitcher_images/David Hernandez_zone_frequency.png";}
if (pitcher=="456696"){document.getElementById("pitch_bar").src = "static/pitcher_images/David Hernandez_zone_frequency_bar.png";}
if (pitcher=="457429"){document.getElementById("pitch_heat").src = "static/pitcher_images/Boone Logan_zone_frequency.png";}
if (pitcher=="457429"){document.getElementById("pitch_bar").src = "static/pitcher_images/Boone Logan_zone_frequency_bar.png";}
if (pitcher=="457732"){document.getElementById("pitch_heat").src = "static/pitcher_images/Andrew Bailey_zone_frequency.png";}
if (pitcher=="457732"){document.getElementById("pitch_bar").src = "static/pitcher_images/Andrew Bailey_zone_frequency_bar.png";}
if (pitcher=="457768"){document.getElementById("pitch_heat").src = "static/pitcher_images/Bryan Morris_zone_frequency.png";}
if (pitcher=="457768"){document.getElementById("pitch_bar").src = "static/pitcher_images/Bryan Morris_zone_frequency_bar.png";}
if (pitcher=="458006"){document.getElementById("pitch_heat").src = "static/pitcher_images/Matt Albers_zone_frequency.png";}
if (pitcher=="458006"){document.getElementById("pitch_bar").src = "static/pitcher_images/Matt Albers_zone_frequency_bar.png";}
if (pitcher=="458584"){document.getElementById("pitch_heat").src = "static/pitcher_images/Xavier Cedeno_zone_frequency.png";}
if (pitcher=="458584"){document.getElementById("pitch_bar").src = "static/pitcher_images/Xavier Cedeno_zone_frequency_bar.png";}
if (pitcher=="458677"){document.getElementById("pitch_heat").src = "static/pitcher_images/Justin Wilson_zone_frequency.png";}
if (pitcher=="458677"){document.getElementById("pitch_bar").src = "static/pitcher_images/Justin Wilson_zone_frequency_bar.png";}
if (pitcher=="458708"){document.getElementById("pitch_heat").src = "static/pitcher_images/Josh Tomlin_zone_frequency.png";}
if (pitcher=="458708"){document.getElementById("pitch_bar").src = "static/pitcher_images/Josh Tomlin_zone_frequency_bar.png";}
if (pitcher=="459429"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jake McGee_zone_frequency.png";}
if (pitcher=="459429"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jake McGee_zone_frequency_bar.png";}
if (pitcher=="460024"){document.getElementById("pitch_heat").src = "static/pitcher_images/Luke Hochevar_zone_frequency.png";}
if (pitcher=="460024"){document.getElementById("pitch_bar").src = "static/pitcher_images/Luke Hochevar_zone_frequency_bar.png";}
if (pitcher=="460059"){document.getElementById("pitch_heat").src = "static/pitcher_images/Mike Pelfrey_zone_frequency.png";}
if (pitcher=="460059"){document.getElementById("pitch_bar").src = "static/pitcher_images/Mike Pelfrey_zone_frequency_bar.png";}
if (pitcher=="460283"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jerry Blevins_zone_frequency.png";}
if (pitcher=="460283"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jerry Blevins_zone_frequency_bar.png";}
if (pitcher=="461325"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tyler Clippard_zone_frequency.png";}
if (pitcher=="461325"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tyler Clippard_zone_frequency_bar.png";}
if (pitcher=="461829"){document.getElementById("pitch_heat").src = "static/pitcher_images/Gio Gonzalez_zone_frequency.png";}
if (pitcher=="461829"){document.getElementById("pitch_bar").src = "static/pitcher_images/Gio Gonzalez_zone_frequency_bar.png";}
if (pitcher=="461833"){document.getElementById("pitch_heat").src = "static/pitcher_images/Phil Hughes_zone_frequency.png";}
if (pitcher=="461833"){document.getElementById("pitch_bar").src = "static/pitcher_images/Phil Hughes_zone_frequency_bar.png";}
if (pitcher=="462136"){document.getElementById("pitch_heat").src = "static/pitcher_images/Marco Estrada_zone_frequency.png";}
if (pitcher=="462136"){document.getElementById("pitch_bar").src = "static/pitcher_images/Marco Estrada_zone_frequency_bar.png";}
if (pitcher=="462382"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jim Johnson_zone_frequency.png";}
if (pitcher=="462382"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jim Johnson_zone_frequency_bar.png";}
if (pitcher=="465657"){document.getElementById("pitch_heat").src = "static/pitcher_images/Joakim Soria_zone_frequency.png";}
if (pitcher=="465657"){document.getElementById("pitch_bar").src = "static/pitcher_images/Joakim Soria_zone_frequency_bar.png";}
if (pitcher=="467008"){document.getElementById("pitch_heat").src = "static/pitcher_images/Pedro Strop_zone_frequency.png";}
if (pitcher=="467008"){document.getElementById("pitch_bar").src = "static/pitcher_images/Pedro Strop_zone_frequency_bar.png";}
if (pitcher=="467100"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ivan Nova_zone_frequency.png";}
if (pitcher=="467100"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ivan Nova_zone_frequency_bar.png";}
if (pitcher=="468396"){document.getElementById("pitch_heat").src = "static/pitcher_images/Alexi Ogando_zone_frequency.png";}
if (pitcher=="468396"){document.getElementById("pitch_bar").src = "static/pitcher_images/Alexi Ogando_zone_frequency_bar.png";}
if (pitcher=="468504"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jhoulys Chacin_zone_frequency.png";}
if (pitcher=="468504"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jhoulys Chacin_zone_frequency_bar.png";}
if (pitcher=="471822"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jumbo Diaz_zone_frequency.png";}
if (pitcher=="471822"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jumbo Diaz_zone_frequency_bar.png";}
if (pitcher=="471911"){document.getElementById("pitch_heat").src = "static/pitcher_images/Carlos Carrasco_zone_frequency.png";}
if (pitcher=="471911"){document.getElementById("pitch_bar").src = "static/pitcher_images/Carlos Carrasco_zone_frequency_bar.png";}
if (pitcher=="472551"){document.getElementById("pitch_heat").src = "static/pitcher_images/Fernando Abad_zone_frequency.png";}
if (pitcher=="472551"){document.getElementById("pitch_bar").src = "static/pitcher_images/Fernando Abad_zone_frequency_bar.png";}
if (pitcher=="472610"){document.getElementById("pitch_heat").src = "static/pitcher_images/Luis Garcia_zone_frequency.png";}
if (pitcher=="472610"){document.getElementById("pitch_bar").src = "static/pitcher_images/Luis Garcia_zone_frequency_bar.png";}
if (pitcher=="473879"){document.getElementById("pitch_heat").src = "static/pitcher_images/Sam Dyson_zone_frequency.png";}
if (pitcher=="473879"){document.getElementById("pitch_bar").src = "static/pitcher_images/Sam Dyson_zone_frequency_bar.png";}
if (pitcher=="474029"){document.getElementById("pitch_heat").src = "static/pitcher_images/Zach Putnam_zone_frequency.png";}
if (pitcher=="474029"){document.getElementById("pitch_bar").src = "static/pitcher_images/Zach Putnam_zone_frequency_bar.png";}
if (pitcher=="474284"){document.getElementById("pitch_heat").src = "static/pitcher_images/Cory Rasmus_zone_frequency.png";}
if (pitcher=="474284"){document.getElementById("pitch_bar").src = "static/pitcher_images/Cory Rasmus_zone_frequency_bar.png";}
if (pitcher=="474521"){document.getElementById("pitch_heat").src = "static/pitcher_images/Shawn Tolleson_zone_frequency.png";}
if (pitcher=="474521"){document.getElementById("pitch_bar").src = "static/pitcher_images/Shawn Tolleson_zone_frequency_bar.png";}
if (pitcher=="474699"){document.getElementById("pitch_heat").src = "static/pitcher_images/Vance Worley_zone_frequency.png";}
if (pitcher=="474699"){document.getElementById("pitch_bar").src = "static/pitcher_images/Vance Worley_zone_frequency_bar.png";}
if (pitcher=="475243"){document.getElementById("pitch_heat").src = "static/pitcher_images/Travis Wood_zone_frequency.png";}
if (pitcher=="475243"){document.getElementById("pitch_bar").src = "static/pitcher_images/Travis Wood_zone_frequency_bar.png";}
if (pitcher=="475479"){document.getElementById("pitch_heat").src = "static/pitcher_images/David Phelps_zone_frequency.png";}
if (pitcher=="475479"){document.getElementById("pitch_bar").src = "static/pitcher_images/David Phelps_zone_frequency_bar.png";}
if (pitcher=="476451"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jeremy Hellickson_zone_frequency.png";}
if (pitcher=="476451"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jeremy Hellickson_zone_frequency_bar.png";}
if (pitcher=="476454"){document.getElementById("pitch_heat").src = "static/pitcher_images/Dellin Betances_zone_frequency.png";}
if (pitcher=="476454"){document.getElementById("pitch_bar").src = "static/pitcher_images/Dellin Betances_zone_frequency_bar.png";}
if (pitcher=="476589"){document.getElementById("pitch_heat").src = "static/pitcher_images/Adam Warren_zone_frequency.png";}
if (pitcher=="476589"){document.getElementById("pitch_bar").src = "static/pitcher_images/Adam Warren_zone_frequency_bar.png";}
if (pitcher=="477003"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jon Niese_zone_frequency.png";}
if (pitcher=="477003"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jon Niese_zone_frequency_bar.png";}
if (pitcher=="477132"){document.getElementById("pitch_heat").src = "static/pitcher_images/Clayton Kershaw_zone_frequency.png";}
if (pitcher=="477132"){document.getElementById("pitch_bar").src = "static/pitcher_images/Clayton Kershaw_zone_frequency_bar.png";}
if (pitcher=="477569"){document.getElementById("pitch_heat").src = "static/pitcher_images/Fernando Salas_zone_frequency.png";}
if (pitcher=="477569"){document.getElementById("pitch_bar").src = "static/pitcher_images/Fernando Salas_zone_frequency_bar.png";}
if (pitcher=="488768"){document.getElementById("pitch_heat").src = "static/pitcher_images/Andrew Cashner_zone_frequency.png";}
if (pitcher=="488768"){document.getElementById("pitch_bar").src = "static/pitcher_images/Andrew Cashner_zone_frequency_bar.png";}
if (pitcher=="488786"){document.getElementById("pitch_heat").src = "static/pitcher_images/Louis Coleman_zone_frequency.png";}
if (pitcher=="488786"){document.getElementById("pitch_bar").src = "static/pitcher_images/Louis Coleman_zone_frequency_bar.png";}
if (pitcher=="489119"){document.getElementById("pitch_heat").src = "static/pitcher_images/Wade Miley_zone_frequency.png";}
if (pitcher=="489119"){document.getElementById("pitch_bar").src = "static/pitcher_images/Wade Miley_zone_frequency_bar.png";}
if (pitcher=="489446"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kirby Yates_zone_frequency.png";}
if (pitcher=="489446"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kirby Yates_zone_frequency_bar.png";}
if (pitcher=="491646"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jeanmar Gomez_zone_frequency.png";}
if (pitcher=="491646"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jeanmar Gomez_zone_frequency_bar.png";}
if (pitcher=="491703"){document.getElementById("pitch_heat").src = "static/pitcher_images/Neftali Feliz_zone_frequency.png";}
if (pitcher=="491703"){document.getElementById("pitch_bar").src = "static/pitcher_images/Neftali Feliz_zone_frequency_bar.png";}
if (pitcher=="491708"){document.getElementById("pitch_heat").src = "static/pitcher_images/Arquimedes Caminero_zone_frequency.png";}
if (pitcher=="491708"){document.getElementById("pitch_bar").src = "static/pitcher_images/Arquimedes Caminero_zone_frequency_bar.png";}
if (pitcher=="493157"){document.getElementById("pitch_heat").src = "static/pitcher_images/Koji Uehara_zone_frequency.png";}
if (pitcher=="493157"){document.getElementById("pitch_bar").src = "static/pitcher_images/Koji Uehara_zone_frequency_bar.png";}
if (pitcher=="500779"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jose Quintana_zone_frequency.png";}
if (pitcher=="500779"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jose Quintana_zone_frequency_bar.png";}
if (pitcher=="501381"){document.getElementById("pitch_heat").src = "static/pitcher_images/Michael Pineda_zone_frequency.png";}
if (pitcher=="501381"){document.getElementById("pitch_bar").src = "static/pitcher_images/Michael Pineda_zone_frequency_bar.png";}
if (pitcher=="501593"){document.getElementById("pitch_heat").src = "static/pitcher_images/Luis Avilan_zone_frequency.png";}
if (pitcher=="501593"){document.getElementById("pitch_bar").src = "static/pitcher_images/Luis Avilan_zone_frequency_bar.png";}
if (pitcher=="501625"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jose Alvarez_zone_frequency.png";}
if (pitcher=="501625"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jose Alvarez_zone_frequency_bar.png";}
if (pitcher=="501789"){document.getElementById("pitch_heat").src = "static/pitcher_images/Will Harris_zone_frequency.png";}
if (pitcher=="501789"){document.getElementById("pitch_bar").src = "static/pitcher_images/Will Harris_zone_frequency_bar.png";}
if (pitcher=="501822"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chris Hatcher_zone_frequency.png";}
if (pitcher=="501822"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chris Hatcher_zone_frequency_bar.png";}
if (pitcher=="501925"){document.getElementById("pitch_heat").src = "static/pitcher_images/Joe Smith_zone_frequency.png";}
if (pitcher=="501925"){document.getElementById("pitch_bar").src = "static/pitcher_images/Joe Smith_zone_frequency_bar.png";}
if (pitcher=="501955"){document.getElementById("pitch_heat").src = "static/pitcher_images/Joba Chamberlain_zone_frequency.png";}
if (pitcher=="501955"){document.getElementById("pitch_bar").src = "static/pitcher_images/Joba Chamberlain_zone_frequency_bar.png";}
if (pitcher=="501957"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chris Tillman_zone_frequency.png";}
if (pitcher=="501957"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chris Tillman_zone_frequency_bar.png";}
if (pitcher=="501992"){document.getElementById("pitch_heat").src = "static/pitcher_images/Nate Karns_zone_frequency.png";}
if (pitcher=="501992"){document.getElementById("pitch_bar").src = "static/pitcher_images/Nate Karns_zone_frequency_bar.png";}
if (pitcher=="502009"){document.getElementById("pitch_heat").src = "static/pitcher_images/Mat Latos_zone_frequency.png";}
if (pitcher=="502009"){document.getElementById("pitch_bar").src = "static/pitcher_images/Mat Latos_zone_frequency_bar.png";}
if (pitcher=="502026"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jeremy Jeffress_zone_frequency.png";}
if (pitcher=="502026"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jeremy Jeffress_zone_frequency_bar.png";}
if (pitcher=="502028"){document.getElementById("pitch_heat").src = "static/pitcher_images/Blake Wood_zone_frequency.png";}
if (pitcher=="502028"){document.getElementById("pitch_bar").src = "static/pitcher_images/Blake Wood_zone_frequency_bar.png";}
if (pitcher=="502032"){document.getElementById("pitch_heat").src = "static/pitcher_images/Bud Norris_zone_frequency.png";}
if (pitcher=="502032"){document.getElementById("pitch_bar").src = "static/pitcher_images/Bud Norris_zone_frequency_bar.png";}
if (pitcher=="502042"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chris Archer_zone_frequency.png";}
if (pitcher=="502042"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chris Archer_zone_frequency_bar.png";}
if (pitcher=="502043"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kyle Gibson_zone_frequency.png";}
if (pitcher=="502043"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kyle Gibson_zone_frequency_bar.png";}
if (pitcher=="502046"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jeff Locke_zone_frequency.png";}
if (pitcher=="502046"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jeff Locke_zone_frequency_bar.png";}
if (pitcher=="502083"){document.getElementById("pitch_heat").src = "static/pitcher_images/Zach McAllister_zone_frequency.png";}
if (pitcher=="502083"){document.getElementById("pitch_bar").src = "static/pitcher_images/Zach McAllister_zone_frequency_bar.png";}
if (pitcher=="502085"){document.getElementById("pitch_heat").src = "static/pitcher_images/David Robertson_zone_frequency.png";}
if (pitcher=="502085"){document.getElementById("pitch_bar").src = "static/pitcher_images/David Robertson_zone_frequency_bar.png";}
if (pitcher=="502154"){document.getElementById("pitch_heat").src = "static/pitcher_images/Zach Britton_zone_frequency.png";}
if (pitcher=="502154"){document.getElementById("pitch_bar").src = "static/pitcher_images/Zach Britton_zone_frequency_bar.png";}
if (pitcher=="502188"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jeff Samardzija_zone_frequency.png";}
if (pitcher=="502188"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jeff Samardzija_zone_frequency_bar.png";}
if (pitcher=="502190"){document.getElementById("pitch_heat").src = "static/pitcher_images/Mike Leake_zone_frequency.png";}
if (pitcher=="502190"){document.getElementById("pitch_bar").src = "static/pitcher_images/Mike Leake_zone_frequency_bar.png";}
if (pitcher=="502239"){document.getElementById("pitch_heat").src = "static/pitcher_images/Trevor Cahill_zone_frequency.png";}
if (pitcher=="502239"){document.getElementById("pitch_bar").src = "static/pitcher_images/Trevor Cahill_zone_frequency_bar.png";}
if (pitcher=="502272"){document.getElementById("pitch_heat").src = "static/pitcher_images/Casey Fien_zone_frequency.png";}
if (pitcher=="502272"){document.getElementById("pitch_bar").src = "static/pitcher_images/Casey Fien_zone_frequency_bar.png";}
if (pitcher=="502327"){document.getElementById("pitch_heat").src = "static/pitcher_images/Hector Santiago_zone_frequency.png";}
if (pitcher=="502327"){document.getElementById("pitch_bar").src = "static/pitcher_images/Hector Santiago_zone_frequency_bar.png";}
if (pitcher=="502381"){document.getElementById("pitch_heat").src = "static/pitcher_images/Luke Gregerson_zone_frequency.png";}
if (pitcher=="502381"){document.getElementById("pitch_bar").src = "static/pitcher_images/Luke Gregerson_zone_frequency_bar.png";}
if (pitcher=="502593"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jake Petricka_zone_frequency.png";}
if (pitcher=="502593"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jake Petricka_zone_frequency_bar.png";}
if (pitcher=="502624"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chase Anderson_zone_frequency.png";}
if (pitcher=="502624"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chase Anderson_zone_frequency_bar.png";}
if (pitcher=="502706"){document.getElementById("pitch_heat").src = "static/pitcher_images/Derek Holland_zone_frequency.png";}
if (pitcher=="502706"){document.getElementById("pitch_bar").src = "static/pitcher_images/Derek Holland_zone_frequency_bar.png";}
if (pitcher=="502748"){document.getElementById("pitch_heat").src = "static/pitcher_images/Brad Peacock_zone_frequency.png";}
if (pitcher=="502748"){document.getElementById("pitch_bar").src = "static/pitcher_images/Brad Peacock_zone_frequency_bar.png";}
if (pitcher=="503285"){document.getElementById("pitch_heat").src = "static/pitcher_images/Darren O'Day_zone_frequency.png";}
if (pitcher=="503285"){document.getElementById("pitch_bar").src = "static/pitcher_images/Darren O'Day_zone_frequency_bar.png";}
if (pitcher=="503449"){document.getElementById("pitch_heat").src = "static/pitcher_images/Wily Peralta_zone_frequency.png";}
if (pitcher=="503449"){document.getElementById("pitch_bar").src = "static/pitcher_images/Wily Peralta_zone_frequency_bar.png";}
if (pitcher=="504379"){document.getElementById("pitch_heat").src = "static/pitcher_images/Juan Nicasio_zone_frequency.png";}
if (pitcher=="504379"){document.getElementById("pitch_bar").src = "static/pitcher_images/Juan Nicasio_zone_frequency_bar.png";}
if (pitcher=="516910"){document.getElementById("pitch_heat").src = "static/pitcher_images/Carlos Frias_zone_frequency.png";}
if (pitcher=="516910"){document.getElementById("pitch_bar").src = "static/pitcher_images/Carlos Frias_zone_frequency_bar.png";}
if (pitcher=="516969"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kelvin Herrera_zone_frequency.png";}
if (pitcher=="516969"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kelvin Herrera_zone_frequency_bar.png";}
if (pitcher=="517008"){document.getElementById("pitch_heat").src = "static/pitcher_images/Alex Colome_zone_frequency.png";}
if (pitcher=="517008"){document.getElementById("pitch_bar").src = "static/pitcher_images/Alex Colome_zone_frequency_bar.png";}
if (pitcher=="517414"){document.getElementById("pitch_heat").src = "static/pitcher_images/Randall Delgado_zone_frequency.png";}
if (pitcher=="517414"){document.getElementById("pitch_bar").src = "static/pitcher_images/Randall Delgado_zone_frequency_bar.png";}
if (pitcher=="517593"){document.getElementById("pitch_heat").src = "static/pitcher_images/Danny Salazar_zone_frequency.png";}
if (pitcher=="517593"){document.getElementById("pitch_bar").src = "static/pitcher_images/Danny Salazar_zone_frequency_bar.png";}
if (pitcher=="518452"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chad Bettis_zone_frequency.png";}
if (pitcher=="518452"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chad Bettis_zone_frequency_bar.png";}
if (pitcher=="518468"){document.getElementById("pitch_heat").src = "static/pitcher_images/Michael Blazek_zone_frequency.png";}
if (pitcher=="518468"){document.getElementById("pitch_bar").src = "static/pitcher_images/Michael Blazek_zone_frequency_bar.png";}
if (pitcher=="518516"){document.getElementById("pitch_heat").src = "static/pitcher_images/Madison Bumgarner_zone_frequency.png";}
if (pitcher=="518516"){document.getElementById("pitch_bar").src = "static/pitcher_images/Madison Bumgarner_zone_frequency_bar.png";}
if (pitcher=="518553"){document.getElementById("pitch_heat").src = "static/pitcher_images/Steve Cishek_zone_frequency.png";}
if (pitcher=="518553"){document.getElementById("pitch_bar").src = "static/pitcher_images/Steve Cishek_zone_frequency_bar.png";}
if (pitcher=="518617"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jake Diekman_zone_frequency.png";}
if (pitcher=="518617"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jake Diekman_zone_frequency_bar.png";}
if (pitcher=="518633"){document.getElementById("pitch_heat").src = "static/pitcher_images/Danny Duffy_zone_frequency.png";}
if (pitcher=="518633"){document.getElementById("pitch_bar").src = "static/pitcher_images/Danny Duffy_zone_frequency_bar.png";}
if (pitcher=="518693"){document.getElementById("pitch_heat").src = "static/pitcher_images/Sam Freeman_zone_frequency.png";}
if (pitcher=="518693"){document.getElementById("pitch_bar").src = "static/pitcher_images/Sam Freeman_zone_frequency_bar.png";}
if (pitcher=="518715"){document.getElementById("pitch_heat").src = "static/pitcher_images/Cory Gearrin_zone_frequency.png";}
if (pitcher=="518715"){document.getElementById("pitch_bar").src = "static/pitcher_images/Cory Gearrin_zone_frequency_bar.png";}
if (pitcher=="518716"){document.getElementById("pitch_heat").src = "static/pitcher_images/Dillon Gee_zone_frequency.png";}
if (pitcher=="518716"){document.getElementById("pitch_bar").src = "static/pitcher_images/Dillon Gee_zone_frequency_bar.png";}
if (pitcher=="518748"){document.getElementById("pitch_heat").src = "static/pitcher_images/Justin Grimm_zone_frequency.png";}
if (pitcher=="518748"){document.getElementById("pitch_bar").src = "static/pitcher_images/Justin Grimm_zone_frequency_bar.png";}
if (pitcher=="518774"){document.getElementById("pitch_heat").src = "static/pitcher_images/Matt Harvey_zone_frequency.png";}
if (pitcher=="518774"){document.getElementById("pitch_bar").src = "static/pitcher_images/Matt Harvey_zone_frequency_bar.png";}
if (pitcher=="518790"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chris Heston_zone_frequency.png";}
if (pitcher=="518790"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chris Heston_zone_frequency_bar.png";}
if (pitcher=="518858"){document.getElementById("pitch_heat").src = "static/pitcher_images/Nate Jones_zone_frequency.png";}
if (pitcher=="518858"){document.getElementById("pitch_bar").src = "static/pitcher_images/Nate Jones_zone_frequency_bar.png";}
if (pitcher=="518863"){document.getElementById("pitch_heat").src = "static/pitcher_images/Taylor Jordan_zone_frequency.png";}
if (pitcher=="518863"){document.getElementById("pitch_bar").src = "static/pitcher_images/Taylor Jordan_zone_frequency_bar.png";}
if (pitcher=="518875"){document.getElementById("pitch_heat").src = "static/pitcher_images/Shawn Kelley_zone_frequency.png";}
if (pitcher=="518875"){document.getElementById("pitch_bar").src = "static/pitcher_images/Shawn Kelley_zone_frequency_bar.png";}
if (pitcher=="518886"){document.getElementById("pitch_heat").src = "static/pitcher_images/Craig Kimbrel_zone_frequency.png";}
if (pitcher=="518886"){document.getElementById("pitch_bar").src = "static/pitcher_images/Craig Kimbrel_zone_frequency_bar.png";}
if (pitcher=="518927"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tommy Layne_zone_frequency.png";}
if (pitcher=="518927"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tommy Layne_zone_frequency_bar.png";}
if (pitcher=="519043"){document.getElementById("pitch_heat").src = "static/pitcher_images/Matt Moore_zone_frequency.png";}
if (pitcher=="519043"){document.getElementById("pitch_bar").src = "static/pitcher_images/Matt Moore_zone_frequency_bar.png";}
if (pitcher=="519076"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jimmy Nelson_zone_frequency.png";}
if (pitcher=="519076"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jimmy Nelson_zone_frequency_bar.png";}
if (pitcher=="519085"){document.getElementById("pitch_heat").src = "static/pitcher_images/Brett Oberholtzer_zone_frequency.png";}
if (pitcher=="519085"){document.getElementById("pitch_bar").src = "static/pitcher_images/Brett Oberholtzer_zone_frequency_bar.png";}
if (pitcher=="519096"){document.getElementById("pitch_heat").src = "static/pitcher_images/Dan Otero_zone_frequency.png";}
if (pitcher=="519096"){document.getElementById("pitch_bar").src = "static/pitcher_images/Dan Otero_zone_frequency_bar.png";}
if (pitcher=="519141"){document.getElementById("pitch_heat").src = "static/pitcher_images/Drew Pomeranz_zone_frequency.png";}
if (pitcher=="519141"){document.getElementById("pitch_bar").src = "static/pitcher_images/Drew Pomeranz_zone_frequency_bar.png";}
if (pitcher=="519144"){document.getElementById("pitch_heat").src = "static/pitcher_images/Rick Porcello_zone_frequency.png";}
if (pitcher=="519144"){document.getElementById("pitch_bar").src = "static/pitcher_images/Rick Porcello_zone_frequency_bar.png";}
if (pitcher=="519151"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ryan Pressly_zone_frequency.png";}
if (pitcher=="519151"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ryan Pressly_zone_frequency_bar.png";}
if (pitcher=="519186"){document.getElementById("pitch_heat").src = "static/pitcher_images/Matt Reynolds_zone_frequency.png";}
if (pitcher=="519186"){document.getElementById("pitch_bar").src = "static/pitcher_images/Matt Reynolds_zone_frequency_bar.png";}
if (pitcher=="519240"){document.getElementById("pitch_heat").src = "static/pitcher_images/Marc Rzepczynski_zone_frequency.png";}
if (pitcher=="519240"){document.getElementById("pitch_bar").src = "static/pitcher_images/Marc Rzepczynski_zone_frequency_bar.png";}
if (pitcher=="519242"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chris Sale_zone_frequency.png";}
if (pitcher=="519242"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chris Sale_zone_frequency_bar.png";}
if (pitcher=="519322"){document.getElementById("pitch_heat").src = "static/pitcher_images/Drew Storen_zone_frequency.png";}
if (pitcher=="519322"){document.getElementById("pitch_bar").src = "static/pitcher_images/Drew Storen_zone_frequency_bar.png";}
if (pitcher=="519437"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chris Withrow_zone_frequency.png";}
if (pitcher=="519437"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chris Withrow_zone_frequency_bar.png";}
if (pitcher=="519455"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jordan Zimmermann_zone_frequency.png";}
if (pitcher=="519455"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jordan Zimmermann_zone_frequency_bar.png";}
if (pitcher=="520980"){document.getElementById("pitch_heat").src = "static/pitcher_images/Pedro Baez_zone_frequency.png";}
if (pitcher=="520980"){document.getElementById("pitch_bar").src = "static/pitcher_images/Pedro Baez_zone_frequency_bar.png";}
if (pitcher=="521230"){document.getElementById("pitch_heat").src = "static/pitcher_images/Liam Hendriks_zone_frequency.png";}
if (pitcher=="521230"){document.getElementById("pitch_bar").src = "static/pitcher_images/Liam Hendriks_zone_frequency_bar.png";}
if (pitcher=="523989"){document.getElementById("pitch_heat").src = "static/pitcher_images/Rubby De La Rosa_zone_frequency.png";}
if (pitcher=="523989"){document.getElementById("pitch_bar").src = "static/pitcher_images/Rubby De La Rosa_zone_frequency_bar.png";}
if (pitcher=="527048"){document.getElementById("pitch_heat").src = "static/pitcher_images/Martin Perez_zone_frequency.png";}
if (pitcher=="527048"){document.getElementById("pitch_bar").src = "static/pitcher_images/Martin Perez_zone_frequency_bar.png";}
if (pitcher=="527054"){document.getElementById("pitch_heat").src = "static/pitcher_images/Julio Teheran_zone_frequency.png";}
if (pitcher=="527054"){document.getElementById("pitch_bar").src = "static/pitcher_images/Julio Teheran_zone_frequency_bar.png";}
if (pitcher=="532077"){document.getElementById("pitch_heat").src = "static/pitcher_images/Roberto Osuna_zone_frequency.png";}
if (pitcher=="532077"){document.getElementById("pitch_bar").src = "static/pitcher_images/Roberto Osuna_zone_frequency_bar.png";}
if (pitcher=="533167"){document.getElementById("pitch_heat").src = "static/pitcher_images/Matt Shoemaker_zone_frequency.png";}
if (pitcher=="533167"){document.getElementById("pitch_bar").src = "static/pitcher_images/Matt Shoemaker_zone_frequency_bar.png";}
if (pitcher=="534812"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kevin Quackenbush_zone_frequency.png";}
if (pitcher=="534812"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kevin Quackenbush_zone_frequency_bar.png";}
if (pitcher=="534910"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jesse Hahn_zone_frequency.png";}
if (pitcher=="534910"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jesse Hahn_zone_frequency_bar.png";}
if (pitcher=="541640"){document.getElementById("pitch_heat").src = "static/pitcher_images/Erasmo Ramirez_zone_frequency.png";}
if (pitcher=="541640"){document.getElementById("pitch_bar").src = "static/pitcher_images/Erasmo Ramirez_zone_frequency_bar.png";}
if (pitcher=="541652"){document.getElementById("pitch_heat").src = "static/pitcher_images/Bruce Rondon_zone_frequency.png";}
if (pitcher=="541652"){document.getElementById("pitch_bar").src = "static/pitcher_images/Bruce Rondon_zone_frequency_bar.png";}
if (pitcher=="542674"){document.getElementById("pitch_heat").src = "static/pitcher_images/Gonzalez Germen_zone_frequency.png";}
if (pitcher=="542674"){document.getElementById("pitch_bar").src = "static/pitcher_images/Gonzalez Germen_zone_frequency_bar.png";}
if (pitcher=="542882"){document.getElementById("pitch_heat").src = "static/pitcher_images/Matt Andriese_zone_frequency.png";}
if (pitcher=="542882"){document.getElementById("pitch_bar").src = "static/pitcher_images/Matt Andriese_zone_frequency_bar.png";}
if (pitcher=="542960"){document.getElementById("pitch_heat").src = "static/pitcher_images/Brad Brach_zone_frequency.png";}
if (pitcher=="542960"){document.getElementById("pitch_bar").src = "static/pitcher_images/Brad Brach_zone_frequency_bar.png";}
if (pitcher=="543022"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tyler Chatwood_zone_frequency.png";}
if (pitcher=="543022"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tyler Chatwood_zone_frequency_bar.png";}
if (pitcher=="543037"){document.getElementById("pitch_heat").src = "static/pitcher_images/Gerrit Cole_zone_frequency.png";}
if (pitcher=="543037"){document.getElementById("pitch_bar").src = "static/pitcher_images/Gerrit Cole_zone_frequency_bar.png";}
if (pitcher=="543045"){document.getElementById("pitch_heat").src = "static/pitcher_images/Adam Conley_zone_frequency.png";}
if (pitcher=="543045"){document.getElementById("pitch_bar").src = "static/pitcher_images/Adam Conley_zone_frequency_bar.png";}
if (pitcher=="543054"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jarred Cosart_zone_frequency.png";}
if (pitcher=="543054"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jarred Cosart_zone_frequency_bar.png";}
if (pitcher=="543135"){document.getElementById("pitch_heat").src = "static/pitcher_images/Nathan Eovaldi_zone_frequency.png";}
if (pitcher=="543135"){document.getElementById("pitch_bar").src = "static/pitcher_images/Nathan Eovaldi_zone_frequency_bar.png";}
if (pitcher=="543144"){document.getElementById("pitch_heat").src = "static/pitcher_images/Danny Farquhar_zone_frequency.png";}
if (pitcher=="543144"){document.getElementById("pitch_bar").src = "static/pitcher_images/Danny Farquhar_zone_frequency_bar.png";}
if (pitcher=="543243"){document.getElementById("pitch_heat").src = "static/pitcher_images/Sonny Gray_zone_frequency.png";}
if (pitcher=="543243"){document.getElementById("pitch_bar").src = "static/pitcher_images/Sonny Gray_zone_frequency_bar.png";}
if (pitcher=="543272"){document.getElementById("pitch_heat").src = "static/pitcher_images/Brad Hand_zone_frequency.png";}
if (pitcher=="543272"){document.getElementById("pitch_bar").src = "static/pitcher_images/Brad Hand_zone_frequency_bar.png";}
if (pitcher=="543278"){document.getElementById("pitch_heat").src = "static/pitcher_images/Blaine Hardy_zone_frequency.png";}
if (pitcher=="543278"){document.getElementById("pitch_bar").src = "static/pitcher_images/Blaine Hardy_zone_frequency_bar.png";}
if (pitcher=="543294"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kyle Hendricks_zone_frequency.png";}
if (pitcher=="543294"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kyle Hendricks_zone_frequency_bar.png";}
if (pitcher=="543339"){document.getElementById("pitch_heat").src = "static/pitcher_images/Daniel Hudson_zone_frequency.png";}
if (pitcher=="543339"){document.getElementById("pitch_bar").src = "static/pitcher_images/Daniel Hudson_zone_frequency_bar.png";}
if (pitcher=="543359"){document.getElementById("pitch_heat").src = "static/pitcher_images/Dan Jennings_zone_frequency.png";}
if (pitcher=="543359"){document.getElementById("pitch_bar").src = "static/pitcher_images/Dan Jennings_zone_frequency_bar.png";}
if (pitcher=="543380"){document.getElementById("pitch_heat").src = "static/pitcher_images/Taylor Jungmann_zone_frequency.png";}
if (pitcher=="543380"){document.getElementById("pitch_bar").src = "static/pitcher_images/Taylor Jungmann_zone_frequency_bar.png";}
if (pitcher=="543408"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tom Koehler_zone_frequency.png";}
if (pitcher=="543408"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tom Koehler_zone_frequency_bar.png";}
if (pitcher=="543456"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kyle Lobstein_zone_frequency.png";}
if (pitcher=="543456"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kyle Lobstein_zone_frequency_bar.png";}
if (pitcher=="543475"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jordan Lyles_zone_frequency.png";}
if (pitcher=="543475"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jordan Lyles_zone_frequency_bar.png";}
if (pitcher=="543506"){document.getElementById("pitch_heat").src = "static/pitcher_images/Brandon Maurer_zone_frequency.png";}
if (pitcher=="543506"){document.getElementById("pitch_bar").src = "static/pitcher_images/Brandon Maurer_zone_frequency_bar.png";}
if (pitcher=="543507"){document.getElementById("pitch_heat").src = "static/pitcher_images/Trevor May_zone_frequency.png";}
if (pitcher=="543507"){document.getElementById("pitch_bar").src = "static/pitcher_images/Trevor May_zone_frequency_bar.png";}
if (pitcher=="543521"){document.getElementById("pitch_heat").src = "static/pitcher_images/Collin McHugh_zone_frequency.png";}
if (pitcher=="543521"){document.getElementById("pitch_bar").src = "static/pitcher_images/Collin McHugh_zone_frequency_bar.png";}
if (pitcher=="543548"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tommy Milone_zone_frequency.png";}
if (pitcher=="543548"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tommy Milone_zone_frequency_bar.png";}
if (pitcher=="543557"){document.getElementById("pitch_heat").src = "static/pitcher_images/Mike Montgomery_zone_frequency.png";}
if (pitcher=="543557"){document.getElementById("pitch_bar").src = "static/pitcher_images/Mike Montgomery_zone_frequency_bar.png";}
if (pitcher=="543606"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jake Odorizzi_zone_frequency.png";}
if (pitcher=="543606"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jake Odorizzi_zone_frequency_bar.png";}
if (pitcher=="543699"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tanner Roark_zone_frequency.png";}
if (pitcher=="543699"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tanner Roark_zone_frequency_bar.png";}
if (pitcher=="543734"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chris Rusin_zone_frequency.png";}
if (pitcher=="543734"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chris Rusin_zone_frequency_bar.png";}
if (pitcher=="543746"){document.getElementById("pitch_heat").src = "static/pitcher_images/Rob Scahill_zone_frequency.png";}
if (pitcher=="543746"){document.getElementById("pitch_bar").src = "static/pitcher_images/Rob Scahill_zone_frequency_bar.png";}
if (pitcher=="543766"){document.getElementById("pitch_heat").src = "static/pitcher_images/Bryan Shaw_zone_frequency.png";}
if (pitcher=="543766"){document.getElementById("pitch_bar").src = "static/pitcher_images/Bryan Shaw_zone_frequency_bar.png";}
if (pitcher=="543779"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kevin Siegrist_zone_frequency.png";}
if (pitcher=="543779"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kevin Siegrist_zone_frequency_bar.png";}
if (pitcher=="543883"){document.getElementById("pitch_heat").src = "static/pitcher_images/Nick Vincent_zone_frequency.png";}
if (pitcher=="543883"){document.getElementById("pitch_bar").src = "static/pitcher_images/Nick Vincent_zone_frequency_bar.png";}
if (pitcher=="543900"){document.getElementById("pitch_heat").src = "static/pitcher_images/Daniel Webb_zone_frequency.png";}
if (pitcher=="543900"){document.getElementById("pitch_bar").src = "static/pitcher_images/Daniel Webb_zone_frequency_bar.png";}
if (pitcher=="543935"){document.getElementById("pitch_heat").src = "static/pitcher_images/Alex Wilson_zone_frequency.png";}
if (pitcher=="543935"){document.getElementById("pitch_bar").src = "static/pitcher_images/Alex Wilson_zone_frequency_bar.png";}
if (pitcher=="544727"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jeurys Familia_zone_frequency.png";}
if (pitcher=="544727"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jeurys Familia_zone_frequency_bar.png";}
if (pitcher=="544928"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tyler Lyons_zone_frequency.png";}
if (pitcher=="544928"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tyler Lyons_zone_frequency_bar.png";}
if (pitcher=="544931"){document.getElementById("pitch_heat").src = "static/pitcher_images/Stephen Strasburg_zone_frequency.png";}
if (pitcher=="544931"){document.getElementById("pitch_bar").src = "static/pitcher_images/Stephen Strasburg_zone_frequency_bar.png";}
if (pitcher=="545333"){document.getElementById("pitch_heat").src = "static/pitcher_images/Trevor Bauer_zone_frequency.png";}
if (pitcher=="545333"){document.getElementById("pitch_bar").src = "static/pitcher_images/Trevor Bauer_zone_frequency_bar.png";}
if (pitcher=="547749"){document.getElementById("pitch_heat").src = "static/pitcher_images/Junichi Tazawa_zone_frequency.png";}
if (pitcher=="547749"){document.getElementById("pitch_bar").src = "static/pitcher_images/Junichi Tazawa_zone_frequency_bar.png";}
if (pitcher=="547874"){document.getElementById("pitch_heat").src = "static/pitcher_images/Hisashi Iwakuma_zone_frequency.png";}
if (pitcher=="547874"){document.getElementById("pitch_bar").src = "static/pitcher_images/Hisashi Iwakuma_zone_frequency_bar.png";}
if (pitcher=="547888"){document.getElementById("pitch_heat").src = "static/pitcher_images/Masahiro Tanaka_zone_frequency.png";}
if (pitcher=="547888"){document.getElementById("pitch_bar").src = "static/pitcher_images/Masahiro Tanaka_zone_frequency_bar.png";}
if (pitcher=="548357"){document.getElementById("pitch_heat").src = "static/pitcher_images/Christian Bergman_zone_frequency.png";}
if (pitcher=="548357"){document.getElementById("pitch_bar").src = "static/pitcher_images/Christian Bergman_zone_frequency_bar.png";}
if (pitcher=="554234"){document.getElementById("pitch_heat").src = "static/pitcher_images/Williams Perez_zone_frequency.png";}
if (pitcher=="554234"){document.getElementById("pitch_bar").src = "static/pitcher_images/Williams Perez_zone_frequency_bar.png";}
if (pitcher=="570649"){document.getElementById("pitch_heat").src = "static/pitcher_images/Yordano Ventura_zone_frequency.png";}
if (pitcher=="570649"){document.getElementById("pitch_bar").src = "static/pitcher_images/Yordano Ventura_zone_frequency_bar.png";}
if (pitcher=="571510"){document.getElementById("pitch_heat").src = "static/pitcher_images/Matt Boyd_zone_frequency.png";}
if (pitcher=="571510"){document.getElementById("pitch_bar").src = "static/pitcher_images/Matt Boyd_zone_frequency_bar.png";}
if (pitcher=="571527"){document.getElementById("pitch_heat").src = "static/pitcher_images/David Buchanan_zone_frequency.png";}
if (pitcher=="571527"){document.getElementById("pitch_bar").src = "static/pitcher_images/David Buchanan_zone_frequency_bar.png";}
if (pitcher=="571561"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tony Cingrani_zone_frequency.png";}
if (pitcher=="571561"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tony Cingrani_zone_frequency_bar.png";}
if (pitcher=="571578"){document.getElementById("pitch_heat").src = "static/pitcher_images/Patrick Corbin_zone_frequency.png";}
if (pitcher=="571578"){document.getElementById("pitch_bar").src = "static/pitcher_images/Patrick Corbin_zone_frequency_bar.png";}
if (pitcher=="571666"){document.getElementById("pitch_heat").src = "static/pitcher_images/Mike Fiers_zone_frequency.png";}
if (pitcher=="571666"){document.getElementById("pitch_bar").src = "static/pitcher_images/Mike Fiers_zone_frequency_bar.png";}
if (pitcher=="571704"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ken Giles_zone_frequency.png";}
if (pitcher=="571704"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ken Giles_zone_frequency_bar.png";}
if (pitcher=="571800"){document.getElementById("pitch_heat").src = "static/pitcher_images/Drew Hutchison_zone_frequency.png";}
if (pitcher=="571800"){document.getElementById("pitch_bar").src = "static/pitcher_images/Drew Hutchison_zone_frequency_bar.png";}
if (pitcher=="571871"){document.getElementById("pitch_heat").src = "static/pitcher_images/Ian Krol_zone_frequency.png";}
if (pitcher=="571871"){document.getElementById("pitch_bar").src = "static/pitcher_images/Ian Krol_zone_frequency_bar.png";}
if (pitcher=="571946"){document.getElementById("pitch_heat").src = "static/pitcher_images/Shelby Miller_zone_frequency.png";}
if (pitcher=="571946"){document.getElementById("pitch_bar").src = "static/pitcher_images/Shelby Miller_zone_frequency_bar.png";}
if (pitcher=="572020"){document.getElementById("pitch_heat").src = "static/pitcher_images/James Paxton_zone_frequency.png";}
if (pitcher=="572020"){document.getElementById("pitch_bar").src = "static/pitcher_images/James Paxton_zone_frequency_bar.png";}
if (pitcher=="572070"){document.getElementById("pitch_heat").src = "static/pitcher_images/Garrett Richards_zone_frequency.png";}
if (pitcher=="572070"){document.getElementById("pitch_bar").src = "static/pitcher_images/Garrett Richards_zone_frequency_bar.png";}
if (pitcher=="572096"){document.getElementById("pitch_heat").src = "static/pitcher_images/Trevor Rosenthal_zone_frequency.png";}
if (pitcher=="572096"){document.getElementById("pitch_bar").src = "static/pitcher_images/Trevor Rosenthal_zone_frequency_bar.png";}
if (pitcher=="572140"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tyler Skaggs_zone_frequency.png";}
if (pitcher=="572140"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tyler Skaggs_zone_frequency_bar.png";}
if (pitcher=="572750"){document.getElementById("pitch_heat").src = "static/pitcher_images/Eddie Butler_zone_frequency.png";}
if (pitcher=="572750"){document.getElementById("pitch_bar").src = "static/pitcher_images/Eddie Butler_zone_frequency_bar.png";}
if (pitcher=="572888"){document.getElementById("pitch_heat").src = "static/pitcher_images/Shane Greene_zone_frequency.png";}
if (pitcher=="572888"){document.getElementById("pitch_bar").src = "static/pitcher_images/Shane Greene_zone_frequency_bar.png";}
if (pitcher=="572971"){document.getElementById("pitch_heat").src = "static/pitcher_images/Dallas Keuchel_zone_frequency.png";}
if (pitcher=="572971"){document.getElementById("pitch_bar").src = "static/pitcher_images/Dallas Keuchel_zone_frequency_bar.png";}
if (pitcher=="573046"){document.getElementById("pitch_heat").src = "static/pitcher_images/Mike Morin_zone_frequency.png";}
if (pitcher=="573046"){document.getElementById("pitch_bar").src = "static/pitcher_images/Mike Morin_zone_frequency_bar.png";}
if (pitcher=="573064"){document.getElementById("pitch_heat").src = "static/pitcher_images/Vidal Nuno_zone_frequency.png";}
if (pitcher=="573064"){document.getElementById("pitch_bar").src = "static/pitcher_images/Vidal Nuno_zone_frequency_bar.png";}
if (pitcher=="573185"){document.getElementById("pitch_heat").src = "static/pitcher_images/Dan Straily_zone_frequency.png";}
if (pitcher=="573185"){document.getElementById("pitch_bar").src = "static/pitcher_images/Dan Straily_zone_frequency_bar.png";}
if (pitcher=="573186"){document.getElementById("pitch_heat").src = "static/pitcher_images/Marcus Stroman_zone_frequency.png";}
if (pitcher=="573186"){document.getElementById("pitch_bar").src = "static/pitcher_images/Marcus Stroman_zone_frequency_bar.png";}
if (pitcher=="592102"){document.getElementById("pitch_heat").src = "static/pitcher_images/Cody Allen_zone_frequency.png";}
if (pitcher=="592102"){document.getElementById("pitch_bar").src = "static/pitcher_images/Cody Allen_zone_frequency_bar.png";}
if (pitcher=="592135"){document.getElementById("pitch_heat").src = "static/pitcher_images/Cam Bedrosian_zone_frequency.png";}
if (pitcher=="592135"){document.getElementById("pitch_bar").src = "static/pitcher_images/Cam Bedrosian_zone_frequency_bar.png";}
if (pitcher=="592314"){document.getElementById("pitch_heat").src = "static/pitcher_images/Mike Foltynewicz_zone_frequency.png";}
if (pitcher=="592314"){document.getElementById("pitch_bar").src = "static/pitcher_images/Mike Foltynewicz_zone_frequency_bar.png";}
if (pitcher=="592346"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chi Chi Gonzalez_zone_frequency.png";}
if (pitcher=="592346"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chi Chi Gonzalez_zone_frequency_bar.png";}
if (pitcher=="592454"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tommy Kahnle_zone_frequency.png";}
if (pitcher=="592454"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tommy Kahnle_zone_frequency_bar.png";}
if (pitcher=="592593"){document.getElementById("pitch_heat").src = "static/pitcher_images/Justin Nicolino_zone_frequency.png";}
if (pitcher=="592593"){document.getElementById("pitch_bar").src = "static/pitcher_images/Justin Nicolino_zone_frequency_bar.png";}
if (pitcher=="592662"){document.getElementById("pitch_heat").src = "static/pitcher_images/Robbie Ray_zone_frequency.png";}
if (pitcher=="592662"){document.getElementById("pitch_bar").src = "static/pitcher_images/Robbie Ray_zone_frequency_bar.png";}
if (pitcher=="592665"){document.getElementById("pitch_heat").src = "static/pitcher_images/Addison Reed_zone_frequency.png";}
if (pitcher=="592665"){document.getElementById("pitch_bar").src = "static/pitcher_images/Addison Reed_zone_frequency_bar.png";}
if (pitcher=="592717"){document.getElementById("pitch_heat").src = "static/pitcher_images/Aaron Sanchez_zone_frequency.png";}
if (pitcher=="592717"){document.getElementById("pitch_bar").src = "static/pitcher_images/Aaron Sanchez_zone_frequency_bar.png";}
if (pitcher=="592741"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chasen Shreve_zone_frequency.png";}
if (pitcher=="592741"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chasen Shreve_zone_frequency_bar.png";}
if (pitcher=="592767"){document.getElementById("pitch_heat").src = "static/pitcher_images/Drew Smyly_zone_frequency.png";}
if (pitcher=="592767"){document.getElementById("pitch_bar").src = "static/pitcher_images/Drew Smyly_zone_frequency_bar.png";}
if (pitcher=="592789"){document.getElementById("pitch_heat").src = "static/pitcher_images/Noah Syndergaard_zone_frequency.png";}
if (pitcher=="592789"){document.getElementById("pitch_bar").src = "static/pitcher_images/Noah Syndergaard_zone_frequency_bar.png";}
if (pitcher=="592804"){document.getElementById("pitch_heat").src = "static/pitcher_images/Tyler Thornburg_zone_frequency.png";}
if (pitcher=="592804"){document.getElementById("pitch_bar").src = "static/pitcher_images/Tyler Thornburg_zone_frequency_bar.png";}
if (pitcher=="592836"){document.getElementById("pitch_heat").src = "static/pitcher_images/Taijuan Walker_zone_frequency.png";}
if (pitcher=="592836"){document.getElementById("pitch_bar").src = "static/pitcher_images/Taijuan Walker_zone_frequency_bar.png";}
if (pitcher=="593372"){document.getElementById("pitch_heat").src = "static/pitcher_images/Carlos Martinez_zone_frequency.png";}
if (pitcher=="593372"){document.getElementById("pitch_bar").src = "static/pitcher_images/Carlos Martinez_zone_frequency_bar.png";}
if (pitcher=="594736"){document.getElementById("pitch_heat").src = "static/pitcher_images/Cody Anderson_zone_frequency.png";}
if (pitcher=="594736"){document.getElementById("pitch_bar").src = "static/pitcher_images/Cody Anderson_zone_frequency_bar.png";}
if (pitcher=="594798"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jacob deGrom_zone_frequency.png";}
if (pitcher=="594798"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jacob deGrom_zone_frequency_bar.png";}
if (pitcher=="594986"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kyle Ryan_zone_frequency.png";}
if (pitcher=="594986"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kyle Ryan_zone_frequency_bar.png";}
if (pitcher=="595014"){document.getElementById("pitch_heat").src = "static/pitcher_images/Blake Treinen_zone_frequency.png";}
if (pitcher=="595014"){document.getElementById("pitch_bar").src = "static/pitcher_images/Blake Treinen_zone_frequency_bar.png";}
if (pitcher=="595307"){document.getElementById("pitch_heat").src = "static/pitcher_images/Seth Maness_zone_frequency.png";}
if (pitcher=="595307"){document.getElementById("pitch_bar").src = "static/pitcher_images/Seth Maness_zone_frequency_bar.png";}
if (pitcher=="605135"){document.getElementById("pitch_heat").src = "static/pitcher_images/Chris Bassitt_zone_frequency.png";}
if (pitcher=="605135"){document.getElementById("pitch_bar").src = "static/pitcher_images/Chris Bassitt_zone_frequency_bar.png";}
if (pitcher=="605177"){document.getElementById("pitch_heat").src = "static/pitcher_images/Andrew Chafin_zone_frequency.png";}
if (pitcher=="605177"){document.getElementById("pitch_bar").src = "static/pitcher_images/Andrew Chafin_zone_frequency_bar.png";}
if (pitcher=="605228"){document.getElementById("pitch_heat").src = "static/pitcher_images/Jose Fernandez_zone_frequency.png";}
if (pitcher=="605228"){document.getElementById("pitch_bar").src = "static/pitcher_images/Jose Fernandez_zone_frequency_bar.png";}
if (pitcher=="605304"){document.getElementById("pitch_heat").src = "static/pitcher_images/Erik Johnson_zone_frequency.png";}
if (pitcher=="605304"){document.getElementById("pitch_bar").src = "static/pitcher_images/Erik Johnson_zone_frequency_bar.png";}
if (pitcher=="605359"){document.getElementById("pitch_heat").src = "static/pitcher_images/Evan Marshall_zone_frequency.png";}
if (pitcher=="605359"){document.getElementById("pitch_bar").src = "static/pitcher_images/Evan Marshall_zone_frequency_bar.png";}
if (pitcher=="605388"){document.getElementById("pitch_heat").src = "static/pitcher_images/Adam Morgan_zone_frequency.png";}
if (pitcher=="605388"){document.getElementById("pitch_bar").src = "static/pitcher_images/Adam Morgan_zone_frequency_bar.png";}
if (pitcher=="605400"){document.getElementById("pitch_heat").src = "static/pitcher_images/Aaron Nola_zone_frequency.png";}
if (pitcher=="605400"){document.getElementById("pitch_bar").src = "static/pitcher_images/Aaron Nola_zone_frequency_bar.png";}
if (pitcher=="605452"){document.getElementById("pitch_heat").src = "static/pitcher_images/Joe Ross_zone_frequency.png";}
if (pitcher=="605452"){document.getElementById("pitch_bar").src = "static/pitcher_images/Joe Ross_zone_frequency_bar.png";}
if (pitcher=="605538"){document.getElementById("pitch_heat").src = "static/pitcher_images/Matt Wisler_zone_frequency.png";}
if (pitcher=="605538"){document.getElementById("pitch_bar").src = "static/pitcher_images/Matt Wisler_zone_frequency_bar.png";}
if (pitcher=="606160"){document.getElementById("pitch_heat").src = "static/pitcher_images/Rafael Montero_zone_frequency.png";}
if (pitcher=="606160"){document.getElementById("pitch_bar").src = "static/pitcher_images/Rafael Montero_zone_frequency_bar.png";}
if (pitcher=="606273"){document.getElementById("pitch_heat").src = "static/pitcher_images/Roenis Elias_zone_frequency.png";}
if (pitcher=="606273"){document.getElementById("pitch_bar").src = "static/pitcher_images/Roenis Elias_zone_frequency_bar.png";}
if (pitcher=="607074"){document.getElementById("pitch_heat").src = "static/pitcher_images/Carlos Rodon_zone_frequency.png";}
if (pitcher=="607074"){document.getElementById("pitch_bar").src = "static/pitcher_images/Carlos Rodon_zone_frequency_bar.png";}
if (pitcher=="607259"){document.getElementById("pitch_heat").src = "static/pitcher_images/Nick Martinez_zone_frequency.png";}
if (pitcher=="607259"){document.getElementById("pitch_bar").src = "static/pitcher_images/Nick Martinez_zone_frequency_bar.png";}
if (pitcher=="607374"){document.getElementById("pitch_heat").src = "static/pitcher_images/Nick Tropeano_zone_frequency.png";}
if (pitcher=="607374"){document.getElementById("pitch_bar").src = "static/pitcher_images/Nick Tropeano_zone_frequency_bar.png";}
if (pitcher=="608379"){document.getElementById("pitch_heat").src = "static/pitcher_images/Michael Wacha_zone_frequency.png";}
if (pitcher=="608379"){document.getElementById("pitch_bar").src = "static/pitcher_images/Michael Wacha_zone_frequency_bar.png";}
if (pitcher=="608665"){document.getElementById("pitch_heat").src = "static/pitcher_images/Kendall Graveman_zone_frequency.png";}
if (pitcher=="608665"){document.getElementById("pitch_bar").src = "static/pitcher_images/Kendall Graveman_zone_frequency_bar.png";}
if (pitcher=="608678"){document.getElementById("pitch_heat").src = "static/pitcher_images/Dominic Leone_zone_frequency.png";}
if (pitcher=="608678"){document.getElementById("pitch_bar").src = "static/pitcher_images/Dominic Leone_zone_frequency_bar.png";}
if (pitcher=="612672"){document.getElementById("pitch_heat").src = "static/pitcher_images/Wei-Yin Chen_zone_frequency.png";}
if (pitcher=="612672"){document.getElementById("pitch_bar").src = "static/pitcher_images/Wei-Yin Chen_zone_frequency_bar.png";}
if (pitcher=="622072"){document.getElementById("pitch_heat").src = "static/pitcher_images/Alex Wood_zone_frequency.png";}
if (pitcher=="622072"){document.getElementById("pitch_bar").src = "static/pitcher_images/Alex Wood_zone_frequency_bar.png";}
if (pitcher=="622663"){document.getElementById("pitch_heat").src = "static/pitcher_images/Luis Severino_zone_frequency.png";}
if (pitcher=="622663"){document.getElementById("pitch_bar").src = "static/pitcher_images/Luis Severino_zone_frequency_bar.png";}
if (pitcher=="623184"){document.getElementById("pitch_heat").src = "static/pitcher_images/Scott Oberg_zone_frequency.png";}
if (pitcher=="623184"){document.getElementById("pitch_bar").src = "static/pitcher_images/Scott Oberg_zone_frequency_bar.png";}
if (pitcher=="628333"){document.getElementById("pitch_heat").src = "static/pitcher_images/Odrisamer Despaigne_zone_frequency.png";}
if (pitcher=="628333"){document.getElementById("pitch_bar").src = "static/pitcher_images/Odrisamer Despaigne_zone_frequency_bar.png";}
if (pitcher=="628452"){document.getElementById("pitch_heat").src = "static/pitcher_images/Raisel Iglesias_zone_frequency.png";}
if (pitcher=="628452"){document.getElementById("pitch_bar").src = "static/pitcher_images/Raisel Iglesias_zone_frequency_bar.png";}
}